"""about_me and last_seen fields

Revision ID: 25b66463496b
Revises: d601ea27c05e
Create Date: 2019-10-19 23:40:16.643777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25b66463496b'
down_revision = 'd601ea27c05e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('app_user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_user', 'last_seen')
    op.drop_column('app_user', 'about_me')
    # ### end Alembic commands ###
