"""adding admin field to AppUser

Revision ID: 314e84a123ca
Revises: 25b66463496b
Create Date: 2019-12-04 21:58:19.613865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '314e84a123ca'
down_revision = '25b66463496b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_user', sa.Column('admin', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_user', 'admin')
    # ### end Alembic commands ###
