"""nominee table

Revision ID: 68f4f2e6075c
Revises: 
Create Date: 2019-09-23 21:16:17.175810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68f4f2e6075c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nominee_lookup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nominee_name', sa.String(length=500), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nominee_lookup_nominee_name'), 'nominee_lookup', ['nominee_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nominee_lookup_nominee_name'), table_name='nominee_lookup')
    op.drop_table('nominee_lookup')
    # ### end Alembic commands ###
