"""completing models

Revision ID: d601ea27c05e
Revises: cfe744395a65
Create Date: 2019-09-23 22:06:08.953196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd601ea27c05e'
down_revision = 'cfe744395a65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=True),
    sa.Column('last_name', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_user_email'), 'app_user', ['email'], unique=True)
    op.create_table('award_lookup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('boost', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category_lookup.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_award_lookup_name'), 'award_lookup', ['name'], unique=True)
    op.create_table('award_winner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_nominee_id', sa.Integer(), nullable=True),
    sa.Column('award_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['award_id'], ['award_lookup.id'], ),
    sa.ForeignKeyConstraint(['category_nominee_id'], ['category_nominee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pick',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_nominee_id', sa.Integer(), nullable=True),
    sa.Column('app_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['app_user_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['category_nominee_id'], ['category_nominee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pick')
    op.drop_table('award_winner')
    op.drop_index(op.f('ix_award_lookup_name'), table_name='award_lookup')
    op.drop_table('award_lookup')
    op.drop_index(op.f('ix_app_user_email'), table_name='app_user')
    op.drop_table('app_user')
    # ### end Alembic commands ###
